### ISSUE TITLE
Infografía Conceptos y fases de gestión de proyectos 

### ISSUE THREAD

**Issue by Jaci14** [SistemasTecTlaxiaco/infografia-Jaci14-1#2]
![1](https://user-images.githubusercontent.com/79876660/132177598-6a007e13-8fc3-4f57-aaac-3efacc0019fa.png)
![2](https://user-images.githubusercontent.com/79876660/132176997-5df3b5ee-c878-44d8-ab49-b0abd2e37daa.png)
![3](https://user-images.githubusercontent.com/79876660/132176999-eae1c603-86af-4905-9f77-bc837d6e30a8.png)

**Comment by MaGuadalupeQuiroz** [comment]
Muy buen trabajo, contiene todos los puntos solicitados y la información es muy interesante.
Calificación: 20%

**Comment by josealfredo79** [comment]
Muy bien hecho y revisado
